### ISSUE TITLE
Missing folder in AFM

### ISSUE THREAD

**Issue by aliantonio** [T0biasCZe/AdbFileManager#1]
AFM is missing a rather large folder that's resident on my phone. Perhaps a size restriction? Screenshots attached.

![Screenshot 2023-07-25 090640](https://github.com/T0biasCZe/AdbFileManager/assets/24923847/29df8f65-1b43-49b1-bb94-3ceaf06f8150)
![Screenshot_20230725-090623](https://github.com/T0biasCZe/AdbFileManager/assets/24923847/ae17d04f-e30b-4921-be45-6e577a2499cb)

**Comment by T0biasCZe** [comment]
try to open cmd in the program folder and run "adb shell ls -l /sdcard/SwiftBackup/"

to open cmd in the folder, go to the folder where the program is stored (in windows explorer), and write cmd in the address bar and hit enter

**Comment by aliantonio** [comment]
It shows up properly in cmd
![Screenshot 2023-07-25 111942](https://github.com/T0biasCZe/AdbFileManager/assets/24923847/9338e32a-7d47-4de5-97ab-e6debe373258)

**Comment by T0biasCZe** [comment]
Try this build, and tell me what error it writes in the console
[Uploading net7.0-windows.zip…]()

**Comment by aliantonio** [comment]
No error, just lists out the directory with the proper folders like the screenshot above.

**Comment by krilok** [comment]
Don't know if it could be related to this issue or a limitation in the app, but the folders under ''Android/media'' can't be accessed either... If I try to open any of them, a popup appears showing the file/size/date, but can't navigate any further... 

Another small quirk... If I simultaneously copy several folders to the phone and then hit refresh directory on the AFM app, the last of the copied folders won't show in the list, even though it has actually been copied correctly (any file browser on the phone shows the folder is there). If I then copy another folder and again hit refresh, this last folder won't appear but the one that was missing previously will now show, and so on and so forth...   

As for the transfer speed of any copied files, I must say it's amazingly fast. A 500MB file took approximately 25 seconds to transfer, which is really surprising, although it would be great if there was some way to display it's transferring or a speed meter. 

In any event, great work so far, and look forward to future updates...

**Comment by krilok** [comment]
> > Don't know if it could be related to this issue or a limitation in the app, but the folders under ''Android/media'' can't be accessed either... If I try to open any of them, a popup appears showing the file/size/date, but can't navigate any further...
> 
> i think access to those is blocked by android
> 
> > although it would be great if there was some way to display it's transferring or a speed meter.
> 
> there is progress bar (but it may be spawned behind the main form...) ![image](https://user-images.githubusercontent.com/44525446/256297607-b4dd9e20-41c7-44bb-a08e-42d9af6c30b4.png)
> 
> > Another small quirk... If I simultaneously copy several folders to the phone and then hit refresh directory on the AFM app, the last of the copied folders won't show in the list, even though it has actually been copied correctly (any file browser on the phone shows the folder is there). If I then copy another folder and again hit refresh, this last folder won't appear but the one that was missing previously will now show, and so on and so forth...
> 
> i think there is bug in the parser that makes it sometimes miss the first file/directory in the list

Thank you for the reply.

Regarding accessing the Android/media folders, that's a pity. Would be quite handy to be able to quickly transfer files from these folders (for example, WhatsApp backups and media). Perhaps in the future it could be implemented?

As for the progress bar, it still doesn't show in my case. Tried latest AFM v3 release and still nothing shows up while transferring, even as you say spawned behind the main window.

**Comment by T0biasCZe** [comment]
> Regarding accessing the Android/media folders, that's a pity. Would be quite handy to be able to quickly transfer files from these folders (for example, WhatsApp backups and media). Perhaps in the future it could be implemented?

it theoretically should work when you manually write the invisible folder name in the address bar

**Comment by krilok** [comment]
> > Regarding accessing the Android/media folders, that's a pity. Would be quite handy to be able to quickly transfer files from these folders (for example, WhatsApp backups and media). Perhaps in the future it could be implemented?
> 
> it theoretically should work when you manually write the invisible folder name in the address bar

Just checked and yes, as you mentioned it indeed copies to the invisible folders by typing the folder name in the address bar.

However, since while or after copying there's no dialogue or confirmation, and hitting refresh on AFM won't list these hidden folders, the only way to actually find out if the copied files/folders where transferred is to browse the phone with a file explorer... 

In any event, it works and could be very handy even if it takes a few steps to get there... Thank you. ;)

**Comment by T0biasCZe** [comment]
Should show them in v1.3.1
