### ISSUE TITLE
Folders with space are listed as empty

### ISSUE THREAD

**Issue by Nojevah** [T0biasCZe/AdbFileManager#12]
When there's a folder with a space in the name, it displays "No files found" whereas there are files.
Version 1.5

Feature request (but don't thing it needs an entry in here): add an icon or an indicator for folders on the left. For now, the only indicator is the size mentionned at 3,371 Kib.

**Comment by T0biasCZe** [comment]
> add an icon or an indicator for folders on the left.

done in sixth release

**Comment by T0biasCZe** [comment]
it should be fixed in v1.7, if you still experience the issue feel free to reopen the isseu
