### ISSUE TITLE
it would be great to have a POPUP with a file name/staus 

### ISSUE THREAD

**Issue by obar1** [T0biasCZe/AdbFileManager#13]

**Comment by T0biasCZe** [comment]
During copying?

**Comment by obar1** [comment]
yes - now it just freeze on a few GB files transfered
it should be easy with another thread or similar :)

**Comment by T0biasCZe** [comment]
well, it should already open a copy dialog, that shows what file is it copying, how many files it already copied, and how many files are being copied total
but its for some reason not visible sometimes on some systems

**Comment by T0biasCZe** [comment]
![image](https://github.com/T0biasCZe/AdbFileManager/assets/44525446/908180c5-6c87-4bb2-8668-20680b803b5e)

**Comment by obar1** [comment]
maybe is my computer (ausus win11)
popup appeared but immmediatily got stuck 
<img width="282" alt="image" src="https://github.com/T0biasCZe/AdbFileManager/assets/387386/6ccece24-b207-4ebb-baa6-93b735cb03c8">

if you have a way me to get some logs - let me know -  thanks

**Comment by T0biasCZe** [comment]
The progress bar only shows progress of how many items were copied from the total number of files of copy                
and when you copy a folder, it counts as 1 file. so the progress bar stays the same until the whole folder is copied, when it will update and increase the number of files already copied

**Comment by obar1** [comment]
ok
ps
this is a cool animation for future release :)
![gif-king-0c5422581144ad1c722605d320604d3a](https://github.com/T0biasCZe/AdbFileManager/assets/387386/e93d2621-1a6e-4db0-9571-f14eaff0baae)
