### ISSUE TITLE
Add Content to Readme - Feature Request + QoL

### ISSUE THREAD

**Issue by Yeehawlerz101** [T0biasCZe/AdbFileManager#14]
Howdy there I had a bit of a rough time getting it working but heres some suggestions to add to the readme for others:
Download the .NET runtime from microsoft
https://dotnet.microsoft.com/en-us/download/dotnet/7.0/runtime
A list of Keys that help navigate the application. (for whatever reason I cant enter a folder that has items in it?)
Other than that This has saved me from reformatting my windows install thank you @T0biasCZe!

**Comment by T0biasCZe** [comment]
done

**Comment by daxsun** [comment]
Cant make it work. Try to run but immediatelly closes. Dont know what im doing wrong
