### ISSUE TITLE
[BUG] Out of memory

### ISSUE THREAD

**Issue by FunFrog-BY** [T0biasCZe/AdbFileManager#15]
**Describe the bug**
It says "Not enough memory etc..." (in russian on my screenshot) and then "Out of memory" when trying to open really big folder. My old phone is S10+ 1TB so camera folder is really big.

**To Reproduce**
1. Go to DCIM
2. Dblclick on Camera
3. Folder name disappears (see screenshot, it's 4th in the list), red stuff in console window appears.

**Expected behavior**
Directory opens, i guess...

**Screenshots**
https://disk.yandex.com/i/xInlYHLA4M9AYQ

**Desktop (please complete the following information):**
 - OS: win11x64
 - 64Gb of RAM

**Additional context**
Gotta go with MTP then.

**Comment by T0biasCZe** [comment]
Hi, please try this build, it should be fixed and work correctly now
[net7.0-windows.zip](https://github.com/T0biasCZe/AdbFileManager/files/13294580/net7.0-windows.zip)

**Comment by FunFrog-BY** [comment]
Hey! Just to confirm.
Same environment, phone and task, last version. Everything works fine.
