### ISSUE TITLE
[BUG] Wrong .Net link in instructions

### ISSUE THREAD

**Issue by tgt26** [T0biasCZe/AdbFileManager#16]
The .Net that is suggested to be installed in the instructions is not the right one. This is the correct one: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-7.0.14-windows-x64-installer

**Comment by T0biasCZe** [comment]
it is the correct one
it takes you to page where you can download the latest version of the runtime for your specific architecture
![image](https://github.com/T0biasCZe/AdbFileManager/assets/44525446/05a9fa03-6984-4d31-a0cf-8d98b98bf319)
