### ISSUE TITLE
[BUG] GUI Problems Multi-Monitor setup + different DPI

### ISSUE THREAD

**Issue by hackgrid** [T0biasCZe/AdbFileManager#20]
**Describe the bug**
I am not sure this is a bug, the latest release looks like this for me:
![grafik](https://github.com/T0biasCZe/AdbFileManager/assets/54060/d8c51af7-8418-499a-b313-b9b43cc31127)

Is the blue bar supposed to be positioned like this?

I use Windows 10 latest + 2x 1080p monitors + 1x 2160p monitor.
The 1080p monitors are on 100% dpi scaling,
the 2160p monitor on 175% scaling.

The GUI looks always like this, it does not matter which monitor I start it from/on.

Maybe you could add a screenshot to the Readme how the GUI is supposed to look?
Also always quite nice for marketing purposes :-)

**Comment by T0biasCZe** [comment]
Fixed, now shows correctly on all DPIs
![image](https://github.com/T0biasCZe/AdbFileManager/assets/44525446/e573273e-6264-43c9-b764-e72b9005078b)

**Comment by hackgrid** [comment]
Great, thanks, I will test it with the next release! :)

**Comment by T0biasCZe** [comment]
it is in seventh release already
![image](https://github.com/T0biasCZe/AdbFileManager/assets/44525446/b391ce26-112a-4cd9-87c0-daf03905ed5a)
