### ISSUE TITLE
[BUG] Does not work with Google Pixel 8

### ISSUE THREAD

**Issue by hackgrid** [T0biasCZe/AdbFileManager#21]
**Describe the bug**
I use a Google Pixel 8 and enabled developer mode + USB debugging.

But the file manager can't find any folders:
![grafik](https://github.com/T0biasCZe/AdbFileManager/assets/54060/80c0d5c1-1a30-445b-a4bb-aa6c873fdfe6)

Maybe there is no real sdcard slot with the Pixel 8?

**Comment by T0biasCZe** [comment]
"/sdcard/" is directory for the internal storage on android phones, not physical sd card

and did you also authorize USB debug for that specific computer? When you enable USB debugging, you also need to separately authorize each computer. When you connect the USB it should show popup dialog if you want to authorize or not

**Comment by hackgrid** [comment]
Thanks, it works now! :-)
I had to delete all previous authorizations + allow it again.

But I had to restart the app, because I was too slow allowing the debugging connection on my phone :-)
Maybe the app could wait for this?

**Comment by T0biasCZe** [comment]
there is refresh button in the middle

**Comment by DiegoFawr** [comment]
Thanks.
Reminder: 

- Allow Developer mode (phone)
- Allow USB Debugging (phone)
- Click 'refresh' (AFM app)
