### ISSUE TITLE
[BUG] I can't copy files with blank spaces in name

### ISSUE THREAD

**Issue by veram17** [T0biasCZe/AdbFileManager#24]
Application doesn't copy files with blank spaces in name. 

![image](https://github.com/T0biasCZe/AdbFileManager/assets/13105881/017db9aa-94fa-40f1-b3ea-d6a8d72fd41a)

![image](https://github.com/T0biasCZe/AdbFileManager/assets/13105881/e43defb6-3b94-468e-a78c-c421855385dd)

**Comment by veram17** [comment]
Parenthesis doesn't work too.

**Comment by T0biasCZe** [comment]
i tried copying files both with spaces, unicode characters and parenthesis and it worked for me, both in normal mode and compatibility mode

could you please show me the detailed exception log under the "details" button? (paste it into code block using \``` at the beggining)

**Comment by T0biasCZe** [comment]
closed due to inactivity
bug with spaces in folder name was fixed 1.9
