### ISSUE TITLE
AdbFileManager.exe doesn't even open in Windows 11

### ISSUE THREAD

**Issue by spss20** [T0biasCZe/AdbFileManager#27]
I even installed .Net Runtime 7.0, still your exe software doesn't open at all.

It just shows a blank terminal window for 2 milliseconds which closes by itself after that.

**Comment by T0biasCZe** [comment]
https://github.com/T0biasCZe/AdbFileManager/releases/tag/dev1%2C9

this is newer release, it shouldnt instantly close at start without showing any error of why it crashed

**Comment by axel-tecnosoul** [comment]
Hi, in Win11 and with .Net Runtime 7.0 installed, the adb.exe file open a windows and instantlly closes. Even with this new release

**Comment by T0biasCZe** [comment]
open AdbFileManager.exe, not adb.exe

**Comment by axel-tecnosoul** [comment]
I don't find this file

**Comment by T0biasCZe** [comment]
thats weird that its missing
I released [new v1.9](https://github.com/T0biasCZe/AdbFileManager/releases), try download that one and check if the file is still missing, it should be there     
![image](https://github.com/user-attachments/assets/87d03933-b2eb-477d-9f80-22664a5e88e0)

**Comment by axel-tecnosoul** [comment]
Sorry, I was downloading the source code! 🤦🏼‍♂️
