### ISSUE TITLE
[BUG] Doesn't work on Windows 10

### ISSUE THREAD

**Issue by Richrdx64** [T0biasCZe/AdbFileManager#31]
I downloaded the .zip file from the latest release of AFM,  I tried opening AdbFileManager.exe, and it didn't work. I downloaded the .NET 7.0 runtime release, tried it again and it didn't work. Am I the only one with this problem? BTW, everytime I open the .exe file, it shows a Command Prompt that closes immediately. Thanks for your time! @T0biasCZe

**Comment by Oltrox** [comment]
try installing this instead the specified in the readme

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=7.0.0&arch=x64&rid=win10-x64

**Comment by Richrdx64** [comment]
@Oltrox Thx!
