### ISSUE TITLE
Inner windows doesn't scale or resize [BUG]

### ISSUE THREAD

**Issue by MrKrota** [T0biasCZe/AdbFileManager#5]
**Describe the bug**
As the title says, I think this can be an easy and great improvement. The inner windows doesn't scale with the app when you try to resize it.

**Comment by JeffryMejia** [comment]
this is how it look on this resolution 2560x1440
![image](https://github.com/T0biasCZe/AdbFileManager/assets/109156257/6db97e9d-4e4c-449b-a819-8fff9921e885)

**Comment by MrKrota** [comment]
exactly, that's what happens with mine too (same res)

**Comment by T0biasCZe** [comment]
Added proper vertical resizing in v1.3 (and locked horizontal)
