### ISSUE TITLE
Use the aplication!?

### ISSUE THREAD

**Issue by sixt00** [T0biasCZe/AdbFileManager#6]
Hello, would someone be so kind as to explain the step by step for the installation of the file?
Specifically 1. what is the compressed folder. 2 downloaded in android is the folder unzipped? and 3,4,5!
Not all of us are programmers but we do work with file transfer from cell phone to PC...

**Comment by T0biasCZe** [comment]
Download the zip on your PC, unzip the compressed folder somewhere, and then run the adbfilemanager.exe

**Comment by sixt00** [comment]
where is the executable please!
[https://drive.google.com/file/d/1-K4wX7Ug8KQ0k64vt9tY7o0QjrIhHsIF/view?usp=sharing](url)

**Comment by nezuky** [comment]
The executable is only included on the [release page](https://github.com/T0biasCZe/AdbFileManager/releases) as `afm.zip`.

You may also build the .exe from source by opening the project in [Visual Studio](https://visualstudio.microsoft.com/downloads/), but you will still need to obtain multiple other files & dlls such as `adb.exe`, `AdbWinApi.dll`, `AdbWinUsbApi.dll`, etc. for the program to work.

Therefore I recommend grabbing the release which has all the necessary files included. Then just run `AdbFileManager.exe` after unzipping the `afm` folder.

**Comment by T0biasCZe** [comment]
go to https://github.com/T0biasCZe/AdbFileManager/releases
download the "AFM.zip" (not the source code (zip))
extract the "AFM.zip"
run the adbfilemanager.exe

**Comment by daxsun** [comment]
When i try to run the program it just flashes and crashes
