### ISSUE TITLE
Feature Request: Include File Timestamps

### ISSUE THREAD

**Issue by nezuky** [T0biasCZe/AdbFileManager#8]
When copying files using Media Transfer Protocol (MTP) file timestamps are preserved.

AdbFileManager does not replicate this behavior, but it can be easily achieved by adding the `-a` flag to `adb pull` so that file timestamps are copied. #7 

Example:
`adb pull -a /sdcard "PC_directory"`

However I don't see an easy solution for implementing timestamps for sending files via `adb push`.

**Comment by T0biasCZe** [comment]
Done in v1.3
